stages:
  - test
  - release

variables:
  INTEGRATION_TESTS: "false"

include:
  - project: 'highload/b2connect/devops/cicd'
    ref: master
    file: 'godefault/.tests.yml'
  - project: 'highload/b2connect/devops/cicd'
    ref: master
    file: 'godefault/.release.yml'
