run:
  deadline: 5m
  issues-exit-code: 1
  tests: false
issues:
  max-same-issues: 15
  max-issues-per-linter: 15

linters-settings:
  govet:
    shadow: true
  gofmt:
    simplify: true
  gocritic:
    settings:
      hugeParam:
        sizeThreshold: 80
    enabled-tags:
      - performance
      - style
      - experimental
      - diagnostic
  gocyclo:
    min-complexity: 50
  misspell:
    locale: US

linters:
  enable:
    - gocyclo
    - gocritic
    - gofmt
    - goconst
    - gosec
    - revive
    - gochecknoinits
    - gosimple
    - unused
    - unconvert
    - unparam
    - misspell
    - nakedret
    - prealloc
    - govet
    - staticcheck
  disable:
    - dupl
    - errcheck
  disable-all: false
